name: Weekly Broadcast
on:
  schedule:
    - cron: "0 12 * * 5"  # JST 19:00
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    env:
      URL: https://line-news-bot-7bh8.onrender.com
      JOB_TOKEN: ${{ secrets.JOB_TOKEN }}

    steps:
      - name: Warm up (wait for Render to wake)
        id: warm
        run: |
          echo "=== Warm-up start ==="
          ATTEMPTS=0
          while [ $ATTEMPTS -lt 10 ]; do
            CODE=$(curl -sS -m 20 -w "%{http_code}" -o /dev/null "$URL/health" || echo "000")
            echo "Attempt $ATTEMPTS => $CODE"
            if [ "$CODE" = "200" ]; then
              echo "Server is awake."
              echo "ok=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
            ATTEMPTS=$((ATTEMPTS + 1))
            sleep 10
          done
          echo "Server did not wake up in time."
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 1

      - name: Trigger broadcast (if warm-up OK)
        if: steps.warm.outputs.ok == 'true'
        run: |
          echo "=== Start broadcast ==="
          TARGET="$URL/broadcast-weekly?to=all-groups"
          CODE=$(curl -sS -m 900 -H "x-job-token: $JOB_TOKEN" -w "%{http_code}" "$TARGET" -o resp.txt || echo "000")
          echo "Broadcast response: $CODE"
          cat resp.txt
          if [ "$CODE" -lt 200 ] || [ "$CODE" -ge 300 ]; then
            echo "Broadcast failed"
            exit 1
          fi
