name: Weekly Broadcast
on:
  schedule:
    - cron: "22 15 * * *" 
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    env:
      URL: https://line-news-bot-7bh8.onrender.com
      JOB_TOKEN: ${{ secrets.JOB_TOKEN }}

    steps:
      - name: Warm up (wait until /health = 200)
        id: warm
        run: |
          echo "=== Warm-up start ==="
          ok=false
          for i in {1..15}; do
            CODE=$(curl -sS -m 20 -w "%{http_code}" -o /dev/null "$URL/health" || echo "000")
            echo "Attempt $i => $CODE"
            if [ "$CODE" = "200" ]; then ok=true; break; fi
            sleep 10
          done
          echo "ok=$ok" >> "$GITHUB_OUTPUT"
          echo "WARM_OK=$ok" >> $GITHUB_ENV

      - name: Trigger broadcast
        if: env.WARM_OK == 'true'
        run: |
          TARGET="$URL/broadcast-weekly?to=all-groups"
          CODE=$(curl -sS -m 900 --retry 3 --retry-delay 6 --retry-all-errors \
                 -H "x-job-token: $JOB_TOKEN" \
                 -w "%{http_code}" "$TARGET" -o resp.txt || echo "000")
          echo "Broadcast HTTP $CODE"
          echo "--- body ---"; cat resp.txt || true; echo "-------------"
          test "$CODE" -ge 200 -a "$CODE" -lt 300