name: Weekly Broadcast
on:
  schedule:
    - cron: "0 9 * * 5"   # JST 18:00
  workflow_dispatch:

jobs:
  call:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      URL: https://line-news-bot-7bh8.onrender.com
      JOB_TOKEN: ${{ secrets.JOB_TOKEN }}
    steps:
      - name: Warm up (check root)
        id: warm
        run: |
          # ルートに最大5回リトライ。HTTPコードを出力へ
          CODE=$(curl -sS -m 60 --retry 5 --retry-delay 5 --retry-all-errors \
                 -w "%{http_code}" "$URL/" -o /dev/null || true)
          echo "Warmup HTTP $CODE"
          echo "code=$CODE" >> "$GITHUB_OUTPUT"

      - name: Trigger broadcast only if warmup OK
        if: steps.warm.outputs.code == '200'
        run: |
          TARGET="$URL/broadcast-weekly?to=all-groups"
          CODE=$(curl -sS -m 120 --retry 3 --retry-delay 6 --retry-all-errors \
                 -H "x-job-token: $JOB_TOKEN" \
                 -w "%{http_code}" "$TARGET" -o resp.txt || true)
          echo "Broadcast HTTP $CODE"
          echo "--- body ---"; cat resp.txt || true; echo "-------------"
          test "$CODE" -ge 200 -a "$CODE" -lt 300
